name: Maven CI

on:
  push:
    branches: [ main, ejerciciosTP1 ]
  pull_request:
    branches: [ main, ejerciciosTP1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
    - name: Run Checkstyle
      run: mvn --batch-mode org.apache.maven.plugins:maven-checkstyle-plugin:3.2.2:check

    - name: Build with Maven (run tests)
      run: mvn -B -DskipTests=false test
